version: '3.8'

networks:
  default:
    name: uxm

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  db:
    image: mysql:8.0.29
    container_name: uxm-db-mysql
    ports:
      - 33306:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: uxm
    platform: linux/x86_64
    restart: always

  db-admin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: uxm-db-admin
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 12345678
    platform: linux/x86_64
    restart: always
